// src/components/calculators/geometri/cirkel.svelte
<script lang="ts">
  import Input from "@components/Svg/Input.svelte";
  import Path from "@components/Svg/Path.svelte";
  import Svg from "@components/Svg/Svg.svelte";
  import Text from "@components/Svg/Text.svelte";
  import Calculator from "@components/calculatorutils/ShapeCalculator.svelte";
  import { Answer, answer, calculator } from "@state/calculator.svelte";
  import { frac, mul, na, pi, pow, bpar, sqrt } from "@math/calculation";
  import { shapeInput } from "@math/utils";
  import Circle from "@components/Svg/Circle.svelte";
  import TextWithKaTeX from "@components/utils/TextWithKaTeX.svelte";

  function getReadonly() {
    if (Object.keys(calculator.valuesFiltered).length === 0) {
      return {
        Omkreds: false,
        Diameter: false,
        Areal: false,
        Radius: false,
      };
    }

    let key = Object.keys(calculator.valuesFiltered)[0];
    return {
      Omkreds: key !== "Omkreds",
      Diameter: key !== "Diameter",
      Areal: key !== "Areal",
      Radius: key !== "Radius",
    };
  }

  let readonly = $derived(getReadonly());

  function calculate() {
    let { Omkreds, Diameter, Areal, Radius } = calculator.opValuesFiltered;

    if (Omkreds) {
      answer.add(
        shapeInput("Omkreds", Omkreds.answer),
        new Answer("Radius", frac(Omkreds, mul(na(2), pi())), "text"),
        new Answer("Diameter", frac(Omkreds, pi()), "text"),
        new Answer(
          "Areal",
          frac(pow(Omkreds, na(2)), mul(na(4), pi())),
          "text",
        ),
      );
    } else if (Diameter) {
      const r = frac(Diameter, na(2));
      answer.add(
        shapeInput("Diameter", Diameter.answer),
        new Answer("Radius", r, "text"),
        new Answer("Omkreds", mul(Diameter, pi()), "text"),
        new Answer("Areal", mul(pow(bpar(r), na(2)), pi()), "text"),
      );
    } else if (Areal) {
      const r = sqrt(frac(Areal, pi()));
      answer.add(
        shapeInput("Areal", Areal.answer),
        new Answer("Radius", r, "text"),
        new Answer("Diameter", mul(r, na(2)), "text"),
        new Answer("Omkreds", mul(mul(r, na(2)), pi()), "text"),
      );
    } else if (Radius) {
      answer.add(
        shapeInput("Radius", Radius.answer),
        new Answer("Diameter", mul(Radius, na(2)), "text"),
        new Answer("Omkreds", mul(mul(Radius, na(2)), pi()), "text"),
        new Answer("Areal", mul(pow(Radius, na(2)), pi()), "text"),
      );
    } else {
      throw new Error("Der er ikke nok informationer til at beregne cirklen");
    }
  }
</script>

<Calculator {calculate}>
  <div class="m-auto hidden h-[500px] w-[600px] text-center sm:block">
    <Input
      name="Omkreds"
      readonly={readonly.Omkreds}
      class="float-left -mb-11 border-blue-500 focus:border-blue-500 focus:ring-blue-500"
    />
    <Input
      name="Diameter"
      readonly={readonly.Diameter}
      class="absolute ml-2 mt-24 border-green-800 focus:border-green-800 focus:ring-green-800"
    />
    <Input
      name="Areal"
      readonly={readonly.Areal}
      class="absolute -ml-48 mt-[12.5rem] border-purple-700 focus:border-purple-600 focus:ring-purple-600"
    />
    <Input
      name="Radius"
      readonly={readonly.Radius}
      class="absolute ml-10 mt-[12.5rem] border-orange-500 focus:border-orange-500 focus:ring-orange-500"
    />

    <Svg width={600} height={500}>
      <Circle x={300} y={250} r={247} class="text-blue-500" />
      <Path d="M 300 3 V 496" class="text-green-800" />
      <Path d="m 300 250 H 546" class="text-orange-500" />

      <Text
        x={340}
        y={270}
        text={answer.has("Radius")
          ? `Radius: ${answer.get("Radius")?.getAns}`
          : ""}
      />
      <Text
        x={310}
        y={155}
        text={answer.has("Diameter")
          ? `Diameter: ${answer.get("Diameter")?.getAns}`
          : ""}
      />
      <Text
        x={0}
        y={60}
        text={answer.has("Omkreds")
          ? `Omkreds: ${answer.get("Omkreds")?.getAns}`
          : ""}
      />
      <Text
        x={110}
        y={260}
        text={answer.has("Areal")
          ? `Areal: ${answer.get("Areal")?.getAns}`
          : ""}
      />
    </Svg>
  </div>

  <div class="m-auto text-center sm:hidden">
    <Svg width={300} height={251}>
      <Circle x={150} y={125.5} r={123.5} class="text-blue-500" />
      <Path d="M 150 3 V 248" class="text-green-800" />
      <Path d="m 150 125.5 H 273" class="text-orange-500" />
    </Svg>
    <Input
      name="Omkreds"
      readonly={readonly.Omkreds}
      class="mx-auto my-1 block border-blue-500 focus:border-blue-500 focus:ring-blue-500"
    />
    <Input
      name="Diameter"
      readonly={readonly.Diameter}
      class="mx-auto my-1 block border-green-800 focus:border-green-800 focus:ring-green-800"
    />
    <Input
      name="Areal"
      readonly={readonly.Areal}
      class="mx-auto my-1 block border-purple-700 focus:border-purple-600 focus:ring-purple-600"
    />
    <Input
      name="Radius"
      readonly={readonly.Radius}
      class="mx-auto my-1 block border-orange-500 focus:border-orange-500 focus:ring-orange-500"
    />
  </div>

  <div class="text-center">
    <TextWithKaTeX text="Pi $(\pi)$ er sat til: ${Math.PI}$" />
  </div>
</Calculator>

// pages/geometri/cirkel.tsx
import { ChangeEvent, useState } from 'react';

import { Calculate } from '@components/Answer';
import Calculator from '@components/Calculator';
import SEO from '@components/SEO';
import Svg, { Circle, Input, Path, Text } from '@components/Svg';

import p from '@utils/Parser';
import { frac, sqrt, text } from '@utils/Tex';

import { AnswerProps } from '@interfaces/index';

export default function Cirkel() {
  const [Radius, setRadius] = useState('');
  const [Diameter, setDiameter] = useState('');
  const [Omkreds, setOmkreds] = useState('');
  const [Areal, setAreal] = useState('');
  const [calculations, setCalculations] = useState<AnswerProps[]>([]);
  const [answers, setAnswers] = useState<Record<string, string | number>>({
    Radius: '',
    Diameter: '',
    Omkreds: '',
    Areal: '',
  });
  const [readonly, setReadonly] = useState({
    Radius: false,
    Diameter: false,
    Omkreds: false,
    Areal: false,
  });

  function calc() {
    const vars = { Radius, Diameter, Areal, Omkreds };

    const answer: Record<string, string | number> = {
      Radius: '',
      Diameter: '',
      Omkreds: '',
      Areal: '',
    };
    const Radius_calc: AnswerProps = { name: 'Radius' };
    const Diameter_calc: AnswerProps = { name: 'Diameter' };
    const Omkreds_calc: AnswerProps = { name: 'Omkreds' };
    const Areal_calc: AnswerProps = { name: 'Areal' };

    if (Radius !== '') {
      answer['Radius'] = Calculate('Radius', vars);
      answer['Diameter'] = Calculate('Radius * 2', vars);
      answer['Omkreds'] = Calculate('Radius * 2 * pi', vars);
      answer['Areal'] = Calculate('Radius^2 * pi', vars);

      Radius_calc.calculation = text(`${p(Radius)} blev indtastet`);
      Diameter_calc.calculation = `${p(Radius)} * 2`;
      Omkreds_calc.calculation = `${p(Radius)} * 2 * \\pi`;
      Areal_calc.calculation = `${p(Radius)}^2 * \\pi`;
    }

    if (Diameter !== '') {
      answer['Radius'] = Calculate('Diameter / 2', vars);
      answer['Diameter'] = Calculate('Diameter', vars);
      answer['Omkreds'] = Calculate('Diameter * pi', vars);
      answer['Areal'] = Calculate('(Diameter / 2)^2 * pi', vars);

      Radius_calc.calculation = frac({ t: p(Diameter), n: 2 });
      Diameter_calc.calculation = text(`${p(Diameter)} blev indtastet`);
      Omkreds_calc.calculation = `${p(Diameter)} * π`;
      Areal_calc.calculation = `(${p(Diameter)} / 2)^2 * \\pi`;
    }

    if (Omkreds !== '') {
      answer['Radius'] = Calculate('Omkreds / (2 * pi)', vars);
      answer['Diameter'] = Calculate('Omkreds / pi', vars);
      answer['Omkreds'] = Calculate('Omkreds', vars);
      answer['Areal'] = Calculate('Omkreds^2 / (4 * pi)', vars);

      Radius_calc.calculation = frac({ t: p(Omkreds), n: '2 * \\pi' });
      Diameter_calc.calculation = frac({ t: p(Omkreds), n: '\\pi' });
      Omkreds_calc.calculation = text(`${p(Omkreds)} blev indtastet`);
      Areal_calc.calculation = frac({ t: `${p(Omkreds)}^2`, n: '4 * \\pi' });
    }

    if (Areal !== '') {
      answer['Radius'] = Calculate('sqrt(Areal / pi)', vars);
      answer['Diameter'] = Calculate('sqrt(Areal / pi) * 2', vars);
      answer['Omkreds'] = Calculate('sqrt(Areal / pi) * 2 * pi', vars);
      answer['Areal'] = Calculate('Areal', vars);

      Radius_calc.calculation = sqrt(frac({ t: p(Areal), n: '\\pi' }));
      Diameter_calc.calculation = `${sqrt(
        frac({ t: p(Areal), n: '\\pi' })
      )} * 2`;
      Omkreds_calc.calculation = `${sqrt(
        frac({ t: p(Areal), n: '\\pi' })
      )} * 2 * \\pi`;
      Areal_calc.calculation = text(`${p(Areal)} blev indtastet`);
    }

    setCalculations([Radius_calc, Diameter_calc, Omkreds_calc, Areal_calc]);
    setAnswers(answer);
  }
  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    let tmp = false;
    if (e.target.value !== '') tmp = true;
    const readonlyTmp = {
      Radius: tmp,
      Diameter: tmp,
      Omkreds: tmp,
      Areal: tmp,
      [e.target.name]: false,
    };

    switch (e.target.name) {
      case 'Radius':
        setRadius(e.target.value);
        break;
      case 'Diameter':
        setDiameter(e.target.value);
        break;
      case 'Omkreds':
        setOmkreds(e.target.value);
        break;
      case 'Areal':
        setAreal(e.target.value);
        break;
    }
    setReadonly(readonlyTmp);
  }
  return (
    <>
      <SEO
        title="Cirkel beregner"
        description="En cirkelberegner der udregner radius, diameter, areal og omkreds af en cirkel"
      />
      <Calculator calculate={calc} answers={calculations}>
        <div className="text-center w-[600px] m-auto h-[500px]">
          <Input
            name="Omkreds"
            value={Omkreds}
            readOnly={readonly['Omkreds']}
            className="-mb-11 border-nord9 focus:ring-nord9 focus:border-nord9 float-left"
            onChange={handleChange}
          />
          <Input
            name="Diameter"
            value={Diameter}
            readOnly={readonly['Diameter']}
            className="border-nord14 focus:ring-nord14 focus:border-nord14 absolute mt-24 ml-2"
            onChange={handleChange}
          />
          <Input
            name="Areal"
            value={Areal}
            readOnly={readonly['Areal']}
            className="absolute mt-[12.5rem] -ml-48 border-nord3 focus:ring-nord10 focus:border-nord10"
            onChange={handleChange}
          />
          <Input
            name="Radius"
            value={Radius}
            readOnly={readonly['Radius']}
            className="absolute mt-[12.5rem] ml-10 border-nord12 focus:ring-nord12 focus:border-nord12"
            onChange={handleChange}
          />
          <Svg width="600" height="500">
            <Circle x="300" y="250" r="247" className="text-nord9" />
            <Path d="M 300 3 V 496" className="text-nord14" />
            <Path d="m 300 250 H 546" className="text-nord12" />

            <Text
              x="340"
              y="270"
              text={answers.Radius && `Radius: ${answers.Radius}`}
            />
            <Text
              x="310"
              y="155"
              text={answers.Diameter && `Diameter: ${answers.Diameter}`}
            />
            <Text
              x="0"
              y="60"
              text={answers.Omkreds && `Omkreds: ${answers.Omkreds}`}
            />
            <Text
              x="110"
              y="260"
              text={answers.Areal && `Areal: ${answers.Areal}`}
            />
          </Svg>
        </div>
        <div>Pi (π) er sat til: {Math.PI}</div>
      </Calculator>
    </>
  );
}
