// pages/renter.tsx
import { ParseAnswer } from '@components/Answer';
import Calculator from '@components/Calculator';
import { AnswerProps, InputProps } from '@interfaces/index';
import { useState } from 'react';

export default function Renter() {
  const [K, setK] = useState('');
  const [r, setr] = useState('');
  const [n, setn] = useState('');
  const [answers, setAnswers] = useState<AnswerProps[]>([]);
  const inputs: InputProps[] = [
    { name: 'K', value: K, onChange: setK, label: 'K (Startkapitalen)' },
    {
      name: 'r',
      value: r,
      onChange: setr,
      label: 'r (Renten i decimaltal. F.eks. er 3% = 0,03)',
    },
    { name: 'n', value: n, onChange: setn, label: 'n (Antal terminer)' },
  ];

  function calc() {
    let int_K = +K;
    let int_r = +r;
    let int_n = +n;

    const Kn = ParseAnswer(int_K * Math.pow(1 + int_r, int_n));

    const KnCalc = (
      <>
        {int_K} * (1 + {int_r})<sup>{int_n}</sup>
      </>
    );

    setAnswers([
      {
        name: (
          <>
            K<sub>n</sub>
          </>
        ),
        answer: Kn,
        calculation: KnCalc,
      },
    ]);
  }
  return <Calculator inputs={inputs} calculate={calc} answers={answers} />;
}

// src/components/Calculators/renter.svelte
<script lang="ts">
  import Inputs from "@components/calculatorutils/inputs/BasicInputs.svelte";
  import { Answer, answer, calculator } from "@state/calculator.svelte";
  import Calculator from "@components/calculatorutils/Calculator.svelte";
  import { add, mul, na, par, pow } from "@math/calculation";

  function calculate() {
    let { K_0, r, n } = calculator.opValues;
    answer.add(new Answer("K_n", mul(K_0, pow(par(add(na(1), r)), n))));
  }
</script>

<Calculator {calculate}>
  <Inputs
    inputs={[
      { name: "K_0", label: "$K_0$ (Startkapitalen)", placeholder: "K₀" },
      {
        name: "r",
        label: "$r$ (Renten i decimaltal. F.eks. er $5\\%$ = $0,05$)",
      },
      { name: "n", label: "$n$ (Antal terminer)" },
    ]}
  />
</Calculator>
